"""Generate own progression functions, advancements, items, recipes and quests.

No third-party content is embedded; compat.py inserts hooks into verified SLB files.
"""
import json
from pathlib import Path
from progression import STAGES, HULL_STAGES
ROOT=Path(__file__).resolve().parents[1]/'overrides'
DATA=ROOT/'kubejs/data/expedition'

def write(path,data):
    path.parent.mkdir(parents=True,exist_ok=True)
    path.write_text(data if isinstance(data,str) else json.dumps(data,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')

def message(text,color='gold'):
    return json.dumps({'text':'[Экспедиция] '+text,'color':color},ensure_ascii=False)

def build():
    objectives=['exp_stage','exp_timer','exp_batch']+[f'exp_b{i}' for i in range(1,10)]+[f'exp_i{i}' for i in range(5)]
    load=['scoreboard objectives add '+o+' dummy' for o in objectives]
    for i in range(1,10):load.append(f'execute unless score $expedition exp_b{i} matches 0.. run scoreboard players set $expedition exp_b{i} 0')
    load += ['execute unless score $expedition exp_stage matches 0.. run scoreboard players set $expedition exp_stage 0',
             'scoreboard players set $expedition exp_timer 0']
    write(DATA/'functions/progression/load.mcfunction','\n'.join(load)+'\n')
    sync=[]
    for i,slug,boss,_,_ in STAGES:
        sync.append(f'execute if score $expedition exp_stage matches {i-1} if score $expedition exp_b{i} matches 1 run function expedition:progression/open/{slug}')
        sync.append(f'execute if score $expedition exp_stage matches {i}.. as @a[advancements={{expedition:stages/{slug}=false}}] run advancement grant @s only expedition:stages/{slug}')
    write(DATA/'functions/progression/sync.mcfunction','\n'.join(sync)+'\n')
    write(DATA/'functions/progression/tick.mcfunction', 'scoreboard players add $expedition exp_timer 1\nexecute if score $expedition exp_timer matches 20.. run function expedition:progression/sync\nexecute if score $expedition exp_timer matches 20.. run scoreboard players set $expedition exp_timer 0\n')
    recipe_js=['// Generated by tools/build_progression.py. Preserve native hull costs.','ServerEvents.recipes(event => {']
    startup=['// Generated by tools/build_progression.py. IDs are world-save identifiers.',"StartupEvents.registry('item', event => {"]
    quests=[]
    dyes=['red','orange','yellow','lime','cyan','blue','purple','magenta','black']
    for i,slug,boss,title,inputs in STAGES:
        write(DATA/f'functions/progression/win/{slug}.mcfunction',
              f'execute unless score $expedition exp_b{i} matches 1 run tellraw @a '+message('Победа: '+boss+'. Она сохранена для всей экспедиции.','green')+'\n'+
              f'scoreboard players set $expedition exp_b{i} 1\nfunction expedition:progression/sync\n')
        write(DATA/f'functions/progression/open/{slug}.mcfunction',f'scoreboard players set $expedition exp_stage {i}\ntellraw @a '+message(f'Открыт этап {i}: {title}. Производство доступно на кузнечном столе по схеме.')+'\n')
        write(DATA/f'advancements/stages/{slug}.json',{'criteria':{'server_unlock':{'trigger':'minecraft:impossible'}}})
        startup.append(f"  event.create('material_{slug}').displayName({json.dumps(title,ensure_ascii=False)}).texture('minecraft:item/amethyst_shard')")
        tip=f'ПКМ схемой по кузнечному столу. Этап {i}; выход 4. Входы: '+', '.join(f'{n} × {item}' for item,n in inputs)
        startup.append(f"  event.create('blueprint_{slug}').displayName({json.dumps('Схема · '+title,ensure_ascii=False)}).texture('minecraft:item/paper').maxStackSize(1).tooltip({json.dumps(tip,ensure_ascii=False)})")
        recipe_js.append(f"  event.shapeless('kubejs:blueprint_{slug}', ['minecraft:paper','minecraft:{dyes[i-1]}_dye']).id('expedition:blueprint_{slug}')")
        lines=[f'execute unless score $expedition exp_stage matches {i}.. run tellraw @s '+message(f'Нужен общий этап {i}: {boss}. Материалы не потрачены.')]
        lines += [f'execute store result score @s exp_i{j} run clear @s {item} 0' for j,(item,_) in enumerate(inputs)]
        condition=' '.join(f'if score @s exp_i{j} matches {count}..' for j,(_,count) in enumerate(inputs))
        lines += ['scoreboard players set @s exp_batch 0',f'execute if score $expedition exp_stage matches {i}.. {condition} run scoreboard players set @s exp_batch 1',
                  f'execute if score $expedition exp_stage matches {i}.. if score @s exp_batch matches 0 run tellraw @s '+message('Не хватает материалов. Состав партии указан в подсказке схемы; ничего не потрачено.'),
                  f'execute if score @s exp_batch matches 1 run function expedition:processing/{slug}/commit']
        write(DATA/f'functions/processing/{slug}/check.mcfunction','\n'.join(lines)+'\n')
        commit=[f'clear @s {item} {count}' for item,count in inputs]+[f'give @s kubejs:material_{slug} 4']
        write(DATA/f'functions/processing/{slug}/commit.mcfunction','\n'.join(commit)+'\n')
        # New advancement task, separate from historical read-only boss cards.
        victory=f'140000000000{i:04X}';material=f'140100000000{i:04X}'
        quests.append({'id':victory,'title':f'{i} · Победа: {boss}','x':float((i-1)*4),'y':0.0,
          'description':['Зачёт по общему серверному этапу после настоящей победы. Предыдущие победы должны быть записаны; ручная галочка атласа ничего не открывает.'],
          'dependencies':[f'140000000000{i-1:04X}'] if i>1 else [],
          'tasks':[{'id':f'250000000000{i:04X}','type':'advancement','advancement':f'expedition:stages/{slug}'}]})
        quests.append({'id':material,'title':title+' · первая партия','x':float((i-1)*4),'y':3.0,
          'description':['Сделайте схему из бумаги и красителя (JEI). Держите её в основной руке и нажмите ПКМ по кузнечному столу; входы должны лежать в вашем инвентаре. Схема многоразовая, выход — 4.','После открытия производите новые партии без повторного фарма босса. Предметы квеста не изымаются.'],
          'dependencies':[victory], 'tasks':[{'id':f'250100000000{i:04X}','type':'item','item':f'kubejs:material_{slug}','count':4,'consume_items':False}]})
    for tier,slug in HULL_STAGES.items():
        title='Переходный компонент '+tier.upper()
        startup.append(f"  event.create('gated_{tier}_component').displayName('{title}').texture('minecraft:item/iron_ingot')")
        original='kubejs:attuned_core' if tier=='lv' else f'gtceu:{tier}_machine_casing'
        recipe_js.append(f"  event.shapeless('kubejs:gated_{tier}_component', ['{original}','kubejs:material_{slug}']).id('expedition:gated_{tier}_component')")
        recipe_js.append(f"  event.replaceInput({{output:'gtceu:{tier}_machine_hull'}}, '{original}', 'kubejs:gated_{tier}_component')")
        if tier=='lv':
            recipe_js.append("  event.replaceInput({output:'gtceu:lv_machine_hull'}, 'gtceu:lv_machine_casing', 'kubejs:gated_lv_component')")
    startup.append('})');recipe_js.append('})')
    write(ROOT/'kubejs/startup_scripts/expedition_progression_items.js','\n'.join(startup)+'\n')
    write(ROOT/'kubejs/server_scripts/expedition_progression_recipes.js','\n'.join(recipe_js)+'\n')
    write(ROOT/'config/ftbquests/quests/chapters/campaign.snbt',{'id':'3000000000000020','filename':'campaign','title':'Основной маршрут · общие открытия','order_index':1,'quests':quests})
    # Keep the historical exp_progress objective; load/tick main entry points remain stable.
    write(DATA/'functions/load.mcfunction','scoreboard objectives add exp_progress dummy\nfunction expedition:progression/load\n')
    write(DATA/'functions/tick.mcfunction','# The old demo notification remains disabled.\nfunction expedition:progression/tick\n')

if __name__=='__main__':build()
